export { default as ModalAddCharacter } from "./Modal_AddCharacter/index";
export { default as ModalAddDialog } from "./Modal_AddDialog/index"
export { default as ModalAddVariable } from "./Modal_AddVariable/index"
export { default as ModalDelete } from "./Modal_Delete/index"
export { default as ModalEditCharacter } from "./Modal_EditCharacter/index"
export { default as ModalEditDialog } from "./Modal_EditDialog/index"
export { default as ModalEditVariable } from "./Modal_EditVariable/index"
export { default as ModalPlayerChoiceTextEditor } from "./Modal_TextEditor/PlayerChoiceTextEditorView"
export { default as ModalTextEditor } from "./Modal_TextEditor/TextEditorView"
export { default as ModalLogin} from "./Modal_Login/AuthModal"
export { default as ModalRegister} from "./Modal_Register/RegisterModal"
export { default as MyProjects} from "./Modal_myProj/ProjectsModal"
