@startuml Онтология ZWorkbench

title WIP Онтология ZWorkbench WIP
skinparam hardwritten true

!workbench                                = "ZWorkbench"
!начало                                    = "Начало"
!проекты                                 = "Проекты"
!редактор                             = "Редактор"
!диспетчер               = "Диспетчер"
!обозреватель                  = "Обозреватель проекта"
!программы                        = "Программы"
!сети                           = "Сети"
!документы                                 = "Документы"
!шаблонныеБлоки                            = "Шаблонные FBD-блоки"
!шаблонныеТаблицаПЗУ                           = "Таблица ПЗУ"
!шаблонныеЖурналСобытий                           = "Журнал Событий"
!шаблонныеРасписание                           = "Расписание"
!библиотекиПроекта                               = "Библиотеки проекта"
!системныеБиблиотеки                                   = "Системные библиотеки"
!контроллеры = "Контроллеры"
!контроллерыСвойства = "Свойства контроллеров"
!контроллерыСвойстваОтладка = "Установка точек отладки на все выходы"
!программа                                 = "FBD-программа"
!опции                                 = "Опции"
!опцииСохранениеВПЗУ = "Сохранение переменных в ПЗУ"
!опцииФлажок = "Флажок Периодически:\nпериодичность записи в ПЗУ в сек"
!опцииПоКоманде = "Флажок «По команде записи по сети»"
!fbdМакрос = "FBD-макрос"
!отладочныйЭкран = "Отладочный экран"
!переменныеКонтроллера = "Переменные контроллера"
!переменныеКонтроллераГруппы = "Аналоговые/дискретные входы/выходы"
!переменныеКонтроллераУниверсальные = "Универсальные входы"
!переменныеКонтроллераСостояние = "Состояние устройства"
!переменныеКонтроллераПараметры = "Диагностика порта"
!свойстваПеременных = "Свойства переменных"
!глобальныеПеременные = "Глобальные переменные"
  !переменнаяНазвание            = "Название гл. пер."
  !переменнаяТипДанных                = "Тип данных"
  !переменнаяНачЗнач                               = "Начальное значение"
  !переменнаяКонстанта                              = "Константа"
  !переменнаяЗаписьВПЗУ                              = "Запись в ПЗУ"
  !переменнаяСетевой                             = "Сетевой доступ"
!блоки = "Блоки"
!блокиКоммент = "Комментировать"
!блокиФункц = "Функциональные блоки"
!блокиМакро = "Макроблоки "
!блокиIOМакро = "Блоки входы/выходы макросов"
!блокиСвойства = "Общие свойства блоков"
!блокиIOСвойстваСимуляция = "Симуляция блоков входов-выходов\nотключение физических входов/выходов контроллера\nи управление ими через панель эмулятора"
!блокиIOСвойства = "Свойства блоков входов-выходов"
!блокиСвойстваНазвание = "Название"
!блокиСвойстваОписание = "Описание"
!блокиСвойстваБлокировка = "Блокировка"
!блокиСвойстваВыводЗаголовка = "Вывод заголовка"
!разныеБлоки = "..."
!триггер = "RS-триггер"
!связи = "Связи"
!связиОбычная = "Обычная связь"
!связиИменованная = "Именованная связь"
!симуляция = "Режим симуляции"
!симуляцияПоШагам = "Симуляция по шагам"
!симуляцияВРеальном = "Симуляция в реальном времени"
!симуляцияОкноотладки = "Окно отладки"
!отладкаIO = "Входы и выходы режима отладки"
!отладкаТочки = "Отладочные точки"
!отладкаТочкиУдалить = "Удалить отл. точки"
!отладкаТочкиДеактивировать = "Деактивировать отл. точки"
!отладкаТочкиПерейтиКВыходу = "Перейты к выходу отл. точки"
!отладочныеТочкиВручную = "Расставить отладочные точки вручную"
!точкиОтладки = "Панель <<Точки отладки>>"
!свойстваОтладочнойТочкиНазвание = "Название точки остановы"
!свойстваОтладочнойТочкиОстановПоУсловию = "Останов по условию"
!свойстваОтладочнойТочкиУсловиеОстанова = "Условие остановы"
!свойстваОтладочнойТочкиКонстанта = "Константа <точка остановы>"

(workbench) --> (начало) : Содержит
(workbench) --> (проекты) : Содержит
(workbench) --> (редактор) : Содержит
(workbench) --> (диспетчер) : Содержит
(редактор) --> (программы) : Содержит
(редактор) --> (сети) : Содержит
(редактор) --> (документы) : Содержит
(редактор) --> (шаблонныеБлоки) : Содержит
(редактор) --> (библиотекиПроекта) : Содержит
(редактор) --> (системныеБиблиотеки) : Содержит
(редактор) --> (симуляция) : Содержит
(редактор) --> (точкиОтладки) : Содержит
(точкиОтладки) --> (свойстваОтладочнойТочки) : Содержит
(свойстваОтладочнойТочки) --> (свойстваОтладочнойТочкиНазвание) : Содержит
(свойстваОтладочнойТочки) --> (свойстваОтладочнойТочкиОстановПоУсловию) : Содержит
(свойстваОтладочнойТочки) --> (свойстваОтладочнойТочкиУсловиеОстанова) : Содержит
(свойстваОтладочнойТочки) --> (свойстваОтладочнойТочкиКонстанта) : Содержит
(симуляция) --> (симуляцияПоШагам) : Содержит
(симуляция) --> (симуляцияВРеальном) : Содержит
(симуляция) --> (симуляцияОкноотладки) : Содержит
(симуляцияОкноотладки) --> (отладкаIO) : Содержит
(симуляцияОкноотладки) --> (отладкаТочки) : Содержит
(отладкаТочки) --> (контроллерыСвойстваОтладка) : Содержит
(отладкаТочки) --> (отладочныеТочкиВручную) : Содержит
(отладкаТочки) --> (отладкаТочкиУдалить) : Содержит
(отладкаТочки) --> (отладкаТочкиДеактивировать) : Содержит
(отладкаТочки) --> (отладкаТочкиПерейтиКВыходу) : Содержит
(шаблонныеБлоки) --> (шаблонныеТаблицаПЗУ) : Содержит
(шаблонныеБлоки) --> (шаблонныеЖурналСобытий) : Содержит
(шаблонныеБлоки) --> (шаблонныеРасписание) : Содержит
(программы) --> (контроллеры) : Содержит
(контроллеры) --> (контроллерыСвойства) : Содержит
(контроллерыСвойства) --> (контроллерыСвойстваОтладка) : Содержит
(контроллеры) --> (программа) : Содержит
(контроллеры) --> (глобальныеПеременные) : Содержит
(контроллеры) --> (переменныеКонтроллера) : Содержит
(переменныеКонтроллера) --> (переменныеКонтроллераГруппы) : Содержит
(переменныеКонтроллера) --> (переменныеКонтроллераУниверсальные) : Содержит
(переменныеКонтроллера) --> (переменныеКонтроллераСостояние) : Содержит
(переменныеКонтроллера) --> (переменныеКонтроллераПараметры) : Содержит
(программа) --> (связи)
(связи) --> (связиОбычная)
(связи) --> (связиИменованная)
(программа) --> (блоки)
(блоки) --> (блокиФункц)
(блоки) --> (блокиМакро)
(блоки) --> (блокиIOМакро)
(блоки) --> (блокиСвойства)
(блоки) --> (блокиIOСвойства)
(блокиIOСвойства) --> [блокиIOСвойстваСимуляция]

(блокиСвойства) --> [блокиСвойстваНазвание]
(блокиСвойства) --> [блокиСвойстваОписание]
(блокиСвойства) --> [блокиСвойстваБлокировка]
(блокиСвойства) --> [блокиСвойстваВыводЗаголовка]
(программа) --> (опции)
(опции) --> (опцииСохранениеВПЗУ)
(опции) --> (опцииФлажок)
(опции) --> (опцииПоКоманде)
(глобальныеПеременные) --> (свойстваПеременных) : Содержит
(свойстваПеременных) --> [переменнаяНазвание] : Состоит из
(свойстваПеременных) --> [переменнаяТипДанных] : Состоит из
(свойстваПеременных) --> [переменнаяНачЗнач] : Состоит из
(свойстваПеременных) --> [переменнаяКонстанта] : Состоит из
(свойстваПеременных) --> [переменнаяЗаписьВПЗУ] : Состоит из
(свойстваПеременных) --> [переменнаяСетевой] : Состоит из


@enduml
